### ISSUE TITLE
Support for floats and doubles

### ISSUE THREAD

**Issue by StandingPadAnimations** [Ryan-rsm-McKenzie/binary_io#4]
Will floats and doubles eventually be supported? If not, what other ways can they be represented?

**Comment by Ryan-rsm-McKenzie** [comment]
floats/doubles are an interesting question because their representations are not universal (`long double` on itanium vs windows), and so trying to abstract them in this library is very difficult. It's a question the reference paper also had a lot of trouble answering as well. If you happen to know that the format and the hardware use the same floating point representation, then you can read a fixed size integer and use `std::bit_cast` to convert to the appropriate floating point type.
